apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
