cloud: aws   # options: aws, gcp, azure

aws:
  region: us-east-1
  project: multi-cloud-devops

gcp:
  region: us-central1
  project: multi-cloud-devops

azure:
  region: eastus
  project: multi-cloud-devops

